# Generated by Django 3.2.9 on 2021-11-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('curso', models.CharField(max_length=80)),
                ('periodo', models.IntegerField()),
                ('interesses', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Interesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=80)),
                ('grau', models.IntegerField()),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
    ]
