# Generated by Django 3.2.9 on 2021-12-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211130_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('pergunta', models.CharField(max_length=255)),
                ('alternativa1', models.CharField(max_length=255)),
                ('alternativa2', models.CharField(max_length=255)),
                ('alternativa3', models.CharField(max_length=255)),
                ('alternativa4', models.CharField(max_length=255)),
                ('alternativa5', models.CharField(max_length=255)),
            ],
        ),
    ]
