# Generated by Django 3.2.9 on 2021-12-03 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_perguntas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='interesses',
        ),
        migrations.CreateModel(
            name='Aluno_Interesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.aluno')),
                ('interesses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.interesses')),
            ],
        ),
    ]
