# Generated by Django 3.2.9 on 2021-12-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20211203_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('imagem', models.CharField(max_length=80)),
                ('texto', models.TextField()),
                ('porc', models.IntegerField()),
            ],
        ),
    ]
